=== femmyblaq/xml-practice/schema.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="library">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="book" maxOccurs="3">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="title" type="xs:string" />
                            <xs:element name="author" type="xs:string" />
                            <xs:element name="publisher" type="xs:string" />
                            <xs:element name="isbn" type="xs:integer" />
                            <xs:element name="price" type="xs:decimal" />
                            <xs:element name="date" type="xs:date" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== femmyblaq/xml-practice/library.xml
<?xml version="1.0" encoding="UTF-8"?>

<library xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="schema.xsd">
    <book>
        <title>Effective Java</title>
        <author>Joshua Bloch</author>
        <publisher>XYZ publisher</publisher>
        <isbn>111234555</isbn>
        <price>120.50</price>
        <date>2000-08-22</date>
    </book>
    <book>
        <title>Python for Beginner</title>
        <author>Bloch</author>
        <publisher>ABC publisher</publisher>
        <isbn>111234555</isbn>
        <price>120.50</price>
        <date>2000-08-22</date>
    </book>
</library>
